#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaSach.MODEL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhaSach")]
	public partial class QLNhaSachDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_CTHOADON(TBL_CTHOADON instance);
    partial void UpdateTBL_CTHOADON(TBL_CTHOADON instance);
    partial void DeleteTBL_CTHOADON(TBL_CTHOADON instance);
    partial void InsertTBL_HOADON(TBL_HOADON instance);
    partial void UpdateTBL_HOADON(TBL_HOADON instance);
    partial void DeleteTBL_HOADON(TBL_HOADON instance);
    partial void InsertTBL_KHACHHANG(TBL_KHACHHANG instance);
    partial void UpdateTBL_KHACHHANG(TBL_KHACHHANG instance);
    partial void DeleteTBL_KHACHHANG(TBL_KHACHHANG instance);
    partial void InsertTBL_KHO(TBL_KHO instance);
    partial void UpdateTBL_KHO(TBL_KHO instance);
    partial void DeleteTBL_KHO(TBL_KHO instance);
    partial void InsertTBL_LOAIPHIEU(TBL_LOAIPHIEU instance);
    partial void UpdateTBL_LOAIPHIEU(TBL_LOAIPHIEU instance);
    partial void DeleteTBL_LOAIPHIEU(TBL_LOAIPHIEU instance);
    partial void InsertTBL_NHANVIEN(TBL_NHANVIEN instance);
    partial void UpdateTBL_NHANVIEN(TBL_NHANVIEN instance);
    partial void DeleteTBL_NHANVIEN(TBL_NHANVIEN instance);
    partial void InsertTBL_NHAXUATBAN(TBL_NHAXUATBAN instance);
    partial void UpdateTBL_NHAXUATBAN(TBL_NHAXUATBAN instance);
    partial void DeleteTBL_NHAXUATBAN(TBL_NHAXUATBAN instance);
    partial void InsertTBL_PHANQUYEN(TBL_PHANQUYEN instance);
    partial void UpdateTBL_PHANQUYEN(TBL_PHANQUYEN instance);
    partial void DeleteTBL_PHANQUYEN(TBL_PHANQUYEN instance);
    partial void InsertTBL_PHIEUCTNHAPXUAT(TBL_PHIEUCTNHAPXUAT instance);
    partial void UpdateTBL_PHIEUCTNHAPXUAT(TBL_PHIEUCTNHAPXUAT instance);
    partial void DeleteTBL_PHIEUCTNHAPXUAT(TBL_PHIEUCTNHAPXUAT instance);
    partial void InsertTBL_PHIEUNHAPXUAT(TBL_PHIEUNHAPXUAT instance);
    partial void UpdateTBL_PHIEUNHAPXUAT(TBL_PHIEUNHAPXUAT instance);
    partial void DeleteTBL_PHIEUNHAPXUAT(TBL_PHIEUNHAPXUAT instance);
    partial void InsertTBL_PHIEUTHUCHI(TBL_PHIEUTHUCHI instance);
    partial void UpdateTBL_PHIEUTHUCHI(TBL_PHIEUTHUCHI instance);
    partial void DeleteTBL_PHIEUTHUCHI(TBL_PHIEUTHUCHI instance);
    partial void InsertTBL_SACH(TBL_SACH instance);
    partial void UpdateTBL_SACH(TBL_SACH instance);
    partial void DeleteTBL_SACH(TBL_SACH instance);
    partial void InsertTBL_TACGIA(TBL_TACGIA instance);
    partial void UpdateTBL_TACGIA(TBL_TACGIA instance);
    partial void DeleteTBL_TACGIA(TBL_TACGIA instance);
    partial void InsertTBL_THELOAI(TBL_THELOAI instance);
    partial void UpdateTBL_THELOAI(TBL_THELOAI instance);
    partial void DeleteTBL_THELOAI(TBL_THELOAI instance);
    partial void InsertTBL_USER(TBL_USER instance);
    partial void UpdateTBL_USER(TBL_USER instance);
    partial void DeleteTBL_USER(TBL_USER instance);
    #endregion
		
		public QLNhaSachDataContext() : 
				base(global::QLNhaSach.Properties.Settings.Default.QLNhaSachConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_CTHOADON> TBL_CTHOADONs
		{
			get
			{
				return this.GetTable<TBL_CTHOADON>();
			}
		}
		
		public System.Data.Linq.Table<TBL_HOADON> TBL_HOADONs
		{
			get
			{
				return this.GetTable<TBL_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KHACHHANG> TBL_KHACHHANGs
		{
			get
			{
				return this.GetTable<TBL_KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KHO> TBL_KHOs
		{
			get
			{
				return this.GetTable<TBL_KHO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_LOAIPHIEU> TBL_LOAIPHIEUs
		{
			get
			{
				return this.GetTable<TBL_LOAIPHIEU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NHANVIEN> TBL_NHANVIENs
		{
			get
			{
				return this.GetTable<TBL_NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NHAXUATBAN> TBL_NHAXUATBANs
		{
			get
			{
				return this.GetTable<TBL_NHAXUATBAN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PHANQUYEN> TBL_PHANQUYENs
		{
			get
			{
				return this.GetTable<TBL_PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PHIEUCTNHAPXUAT> TBL_PHIEUCTNHAPXUATs
		{
			get
			{
				return this.GetTable<TBL_PHIEUCTNHAPXUAT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PHIEUNHAPXUAT> TBL_PHIEUNHAPXUATs
		{
			get
			{
				return this.GetTable<TBL_PHIEUNHAPXUAT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PHIEUTHUCHI> TBL_PHIEUTHUCHIs
		{
			get
			{
				return this.GetTable<TBL_PHIEUTHUCHI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this.GetTable<TBL_SACH>();
			}
		}
		
		public System.Data.Linq.Table<TBL_SODOANHTHU> TBL_SODOANHTHUs
		{
			get
			{
				return this.GetTable<TBL_SODOANHTHU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_TACGIA> TBL_TACGIAs
		{
			get
			{
				return this.GetTable<TBL_TACGIA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_THELOAI> TBL_THELOAIs
		{
			get
			{
				return this.GetTable<TBL_THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USER> TBL_USERs
		{
			get
			{
				return this.GetTable<TBL_USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CTHOADON")]
	public partial class TBL_CTHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHOADON;
		
		private string _MASACH;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<decimal> _DONGIA;
		
		private string _DVT;
		
		private EntityRef<TBL_HOADON> _TBL_HOADON;
		
		private EntityRef<TBL_SACH> _TBL_SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOADONChanging(string value);
    partial void OnMAHOADONChanged();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    #endregion
		
		public TBL_CTHOADON()
		{
			this._TBL_HOADON = default(EntityRef<TBL_HOADON>);
			this._TBL_SACH = default(EntityRef<TBL_SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOADON", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOADON
		{
			get
			{
				return this._MAHOADON;
			}
			set
			{
				if ((this._MAHOADON != value))
				{
					if (this._TBL_HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHOADONChanging(value);
					this.SendPropertyChanging();
					this._MAHOADON = value;
					this.SendPropertyChanged("MAHOADON");
					this.OnMAHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					if (this._TBL_SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_HOADON_TBL_CTHOADON", Storage="_TBL_HOADON", ThisKey="MAHOADON", OtherKey="MAHOADON", IsForeignKey=true)]
		public TBL_HOADON TBL_HOADON
		{
			get
			{
				return this._TBL_HOADON.Entity;
			}
			set
			{
				TBL_HOADON previousValue = this._TBL_HOADON.Entity;
				if (((previousValue != value) 
							|| (this._TBL_HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_HOADON.Entity = null;
						previousValue.TBL_CTHOADONs.Remove(this);
					}
					this._TBL_HOADON.Entity = value;
					if ((value != null))
					{
						value.TBL_CTHOADONs.Add(this);
						this._MAHOADON = value.MAHOADON;
					}
					else
					{
						this._MAHOADON = default(string);
					}
					this.SendPropertyChanged("TBL_HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_SACH_TBL_CTHOADON", Storage="_TBL_SACH", ThisKey="MASACH", OtherKey="MASACH", IsForeignKey=true)]
		public TBL_SACH TBL_SACH
		{
			get
			{
				return this._TBL_SACH.Entity;
			}
			set
			{
				TBL_SACH previousValue = this._TBL_SACH.Entity;
				if (((previousValue != value) 
							|| (this._TBL_SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_SACH.Entity = null;
						previousValue.TBL_CTHOADONs.Remove(this);
					}
					this._TBL_SACH.Entity = value;
					if ((value != null))
					{
						value.TBL_CTHOADONs.Add(this);
						this._MASACH = value.MASACH;
					}
					else
					{
						this._MASACH = default(string);
					}
					this.SendPropertyChanged("TBL_SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_HOADON")]
	public partial class TBL_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHOADON;
		
		private System.Nullable<System.DateTime> _NGAY;
		
		private System.Nullable<decimal> _TONGTIEN;
		
		private string _MAKHACH;
		
		private string _MANV;
		
		private EntitySet<TBL_CTHOADON> _TBL_CTHOADONs;
		
		private EntityRef<TBL_KHACHHANG> _TBL_KHACHHANG;
		
		private EntityRef<TBL_NHANVIEN> _TBL_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOADONChanging(string value);
    partial void OnMAHOADONChanged();
    partial void OnNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYChanged();
    partial void OnTONGTIENChanging(System.Nullable<decimal> value);
    partial void OnTONGTIENChanged();
    partial void OnMAKHACHChanging(string value);
    partial void OnMAKHACHChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    #endregion
		
		public TBL_HOADON()
		{
			this._TBL_CTHOADONs = new EntitySet<TBL_CTHOADON>(new Action<TBL_CTHOADON>(this.attach_TBL_CTHOADONs), new Action<TBL_CTHOADON>(this.detach_TBL_CTHOADONs));
			this._TBL_KHACHHANG = default(EntityRef<TBL_KHACHHANG>);
			this._TBL_NHANVIEN = default(EntityRef<TBL_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOADON", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHOADON
		{
			get
			{
				return this._MAHOADON;
			}
			set
			{
				if ((this._MAHOADON != value))
				{
					this.OnMAHOADONChanging(value);
					this.SendPropertyChanging();
					this._MAHOADON = value;
					this.SendPropertyChanged("MAHOADON");
					this.OnMAHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY", DbType="Date")]
		public System.Nullable<System.DateTime> NGAY
		{
			get
			{
				return this._NGAY;
			}
			set
			{
				if ((this._NGAY != value))
				{
					this.OnNGAYChanging(value);
					this.SendPropertyChanging();
					this._NGAY = value;
					this.SendPropertyChanged("NGAY");
					this.OnNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Money")]
		public System.Nullable<decimal> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACH", DbType="NChar(10)")]
		public string MAKHACH
		{
			get
			{
				return this._MAKHACH;
			}
			set
			{
				if ((this._MAKHACH != value))
				{
					if (this._TBL_KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHACHChanging(value);
					this.SendPropertyChanging();
					this._MAKHACH = value;
					this.SendPropertyChanged("MAKHACH");
					this.OnMAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NChar(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._TBL_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_HOADON_TBL_CTHOADON", Storage="_TBL_CTHOADONs", ThisKey="MAHOADON", OtherKey="MAHOADON")]
		public EntitySet<TBL_CTHOADON> TBL_CTHOADONs
		{
			get
			{
				return this._TBL_CTHOADONs;
			}
			set
			{
				this._TBL_CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_KHACHHANG_TBL_HOADON", Storage="_TBL_KHACHHANG", ThisKey="MAKHACH", OtherKey="MAKH", IsForeignKey=true)]
		public TBL_KHACHHANG TBL_KHACHHANG
		{
			get
			{
				return this._TBL_KHACHHANG.Entity;
			}
			set
			{
				TBL_KHACHHANG previousValue = this._TBL_KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._TBL_KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_KHACHHANG.Entity = null;
						previousValue.TBL_HOADONs.Remove(this);
					}
					this._TBL_KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.TBL_HOADONs.Add(this);
						this._MAKHACH = value.MAKH;
					}
					else
					{
						this._MAKHACH = default(string);
					}
					this.SendPropertyChanged("TBL_KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHANVIEN_TBL_HOADON", Storage="_TBL_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public TBL_NHANVIEN TBL_NHANVIEN
		{
			get
			{
				return this._TBL_NHANVIEN.Entity;
			}
			set
			{
				TBL_NHANVIEN previousValue = this._TBL_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._TBL_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_NHANVIEN.Entity = null;
						previousValue.TBL_HOADONs.Remove(this);
					}
					this._TBL_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TBL_HOADONs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("TBL_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_CTHOADONs(TBL_CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_HOADON = this;
		}
		
		private void detach_TBL_CTHOADONs(TBL_CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KHACHHANG")]
	public partial class TBL_KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKH;
		
		private string _TENKH;
		
		private string _GIOITINH;
		
		private System.Nullable<int> _SDT;
		
		private string _EMAIL;
		
		private string _DIACHI;
		
		private EntitySet<TBL_HOADON> _TBL_HOADONs;
		
		private EntitySet<TBL_PHIEUTHUCHI> _TBL_PHIEUTHUCHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnTENKHChanging(string value);
    partial void OnTENKHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public TBL_KHACHHANG()
		{
			this._TBL_HOADONs = new EntitySet<TBL_HOADON>(new Action<TBL_HOADON>(this.attach_TBL_HOADONs), new Action<TBL_HOADON>(this.detach_TBL_HOADONs));
			this._TBL_PHIEUTHUCHIs = new EntitySet<TBL_PHIEUTHUCHI>(new Action<TBL_PHIEUTHUCHI>(this.attach_TBL_PHIEUTHUCHIs), new Action<TBL_PHIEUTHUCHI>(this.detach_TBL_PHIEUTHUCHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH", DbType="NVarChar(50)")]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this.OnTENKHChanging(value);
					this.SendPropertyChanging();
					this._TENKH = value;
					this.SendPropertyChanged("TENKH");
					this.OnTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(4)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_KHACHHANG_TBL_HOADON", Storage="_TBL_HOADONs", ThisKey="MAKH", OtherKey="MAKHACH")]
		public EntitySet<TBL_HOADON> TBL_HOADONs
		{
			get
			{
				return this._TBL_HOADONs;
			}
			set
			{
				this._TBL_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_KHACHHANG_TBL_PHIEUTHUCHI", Storage="_TBL_PHIEUTHUCHIs", ThisKey="MAKH", OtherKey="MAKHACH")]
		public EntitySet<TBL_PHIEUTHUCHI> TBL_PHIEUTHUCHIs
		{
			get
			{
				return this._TBL_PHIEUTHUCHIs;
			}
			set
			{
				this._TBL_PHIEUTHUCHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_HOADONs(TBL_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_KHACHHANG = this;
		}
		
		private void detach_TBL_HOADONs(TBL_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_KHACHHANG = null;
		}
		
		private void attach_TBL_PHIEUTHUCHIs(TBL_PHIEUTHUCHI entity)
		{
			this.SendPropertyChanging();
			entity.TBL_KHACHHANG = this;
		}
		
		private void detach_TBL_PHIEUTHUCHIs(TBL_PHIEUTHUCHI entity)
		{
			this.SendPropertyChanging();
			entity.TBL_KHACHHANG = null;
		}

        public static explicit operator DataTable(TBL_KHACHHANG v)
        {
            throw new NotImplementedException();
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KHO")]
	public partial class TBL_KHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHO;
		
		private string _TENKHO;
		
		private string _DIACHI;
		
		private EntitySet<TBL_PHIEUNHAPXUAT> _TBL_PHIEUNHAPXUATs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHOChanging(string value);
    partial void OnMAKHOChanged();
    partial void OnTENKHOChanging(string value);
    partial void OnTENKHOChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public TBL_KHO()
		{
			this._TBL_PHIEUNHAPXUATs = new EntitySet<TBL_PHIEUNHAPXUAT>(new Action<TBL_PHIEUNHAPXUAT>(this.attach_TBL_PHIEUNHAPXUATs), new Action<TBL_PHIEUNHAPXUAT>(this.detach_TBL_PHIEUNHAPXUATs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHO", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHO
		{
			get
			{
				return this._MAKHO;
			}
			set
			{
				if ((this._MAKHO != value))
				{
					this.OnMAKHOChanging(value);
					this.SendPropertyChanging();
					this._MAKHO = value;
					this.SendPropertyChanged("MAKHO");
					this.OnMAKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHO", DbType="NVarChar(50)")]
		public string TENKHO
		{
			get
			{
				return this._TENKHO;
			}
			set
			{
				if ((this._TENKHO != value))
				{
					this.OnTENKHOChanging(value);
					this.SendPropertyChanging();
					this._TENKHO = value;
					this.SendPropertyChanged("TENKHO");
					this.OnTENKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_KHO_TBL_PHIEUNHAPXUAT", Storage="_TBL_PHIEUNHAPXUATs", ThisKey="MAKHO", OtherKey="MAKHO")]
		public EntitySet<TBL_PHIEUNHAPXUAT> TBL_PHIEUNHAPXUATs
		{
			get
			{
				return this._TBL_PHIEUNHAPXUATs;
			}
			set
			{
				this._TBL_PHIEUNHAPXUATs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_KHO = this;
		}
		
		private void detach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_KHO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_LOAIPHIEU")]
	public partial class TBL_LOAIPHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAIPHIEU;
		
		private string _TENLOAIPHIEU;
		
		private EntitySet<TBL_PHIEUNHAPXUAT> _TBL_PHIEUNHAPXUATs;
		
		private EntitySet<TBL_PHIEUTHUCHI> _TBL_PHIEUTHUCHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIPHIEUChanging(string value);
    partial void OnMALOAIPHIEUChanged();
    partial void OnTENLOAIPHIEUChanging(string value);
    partial void OnTENLOAIPHIEUChanged();
    #endregion
		
		public TBL_LOAIPHIEU()
		{
			this._TBL_PHIEUNHAPXUATs = new EntitySet<TBL_PHIEUNHAPXUAT>(new Action<TBL_PHIEUNHAPXUAT>(this.attach_TBL_PHIEUNHAPXUATs), new Action<TBL_PHIEUNHAPXUAT>(this.detach_TBL_PHIEUNHAPXUATs));
			this._TBL_PHIEUTHUCHIs = new EntitySet<TBL_PHIEUTHUCHI>(new Action<TBL_PHIEUTHUCHI>(this.attach_TBL_PHIEUTHUCHIs), new Action<TBL_PHIEUTHUCHI>(this.detach_TBL_PHIEUTHUCHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIPHIEU", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAIPHIEU
		{
			get
			{
				return this._MALOAIPHIEU;
			}
			set
			{
				if ((this._MALOAIPHIEU != value))
				{
					this.OnMALOAIPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MALOAIPHIEU = value;
					this.SendPropertyChanged("MALOAIPHIEU");
					this.OnMALOAIPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIPHIEU", DbType="NVarChar(30)")]
		public string TENLOAIPHIEU
		{
			get
			{
				return this._TENLOAIPHIEU;
			}
			set
			{
				if ((this._TENLOAIPHIEU != value))
				{
					this.OnTENLOAIPHIEUChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIPHIEU = value;
					this.SendPropertyChanged("TENLOAIPHIEU");
					this.OnTENLOAIPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_LOAIPHIEU_TBL_PHIEUNHAPXUAT", Storage="_TBL_PHIEUNHAPXUATs", ThisKey="MALOAIPHIEU", OtherKey="MALOAIPHIEU")]
		public EntitySet<TBL_PHIEUNHAPXUAT> TBL_PHIEUNHAPXUATs
		{
			get
			{
				return this._TBL_PHIEUNHAPXUATs;
			}
			set
			{
				this._TBL_PHIEUNHAPXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_LOAIPHIEU_TBL_PHIEUTHUCHI", Storage="_TBL_PHIEUTHUCHIs", ThisKey="MALOAIPHIEU", OtherKey="MALOAIPHIEU")]
		public EntitySet<TBL_PHIEUTHUCHI> TBL_PHIEUTHUCHIs
		{
			get
			{
				return this._TBL_PHIEUTHUCHIs;
			}
			set
			{
				this._TBL_PHIEUTHUCHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_LOAIPHIEU = this;
		}
		
		private void detach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_LOAIPHIEU = null;
		}
		
		private void attach_TBL_PHIEUTHUCHIs(TBL_PHIEUTHUCHI entity)
		{
			this.SendPropertyChanging();
			entity.TBL_LOAIPHIEU = this;
		}
		
		private void detach_TBL_PHIEUTHUCHIs(TBL_PHIEUTHUCHI entity)
		{
			this.SendPropertyChanging();
			entity.TBL_LOAIPHIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NHANVIEN")]
	public partial class TBL_NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENNV;
		
		private string _GIOTINH;
		
		private System.Nullable<int> _CMND;
		
		private string _DIACHI;
		
		private string _CHUCVU;
		
		private EntitySet<TBL_HOADON> _TBL_HOADONs;
		
		private EntitySet<TBL_PHIEUNHAPXUAT> _TBL_PHIEUNHAPXUATs;
		
		private EntitySet<TBL_PHIEUTHUCHI> _TBL_PHIEUTHUCHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnGIOTINHChanging(string value);
    partial void OnGIOTINHChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    #endregion
		
		public TBL_NHANVIEN()
		{
			this._TBL_HOADONs = new EntitySet<TBL_HOADON>(new Action<TBL_HOADON>(this.attach_TBL_HOADONs), new Action<TBL_HOADON>(this.detach_TBL_HOADONs));
			this._TBL_PHIEUNHAPXUATs = new EntitySet<TBL_PHIEUNHAPXUAT>(new Action<TBL_PHIEUNHAPXUAT>(this.attach_TBL_PHIEUNHAPXUATs), new Action<TBL_PHIEUNHAPXUAT>(this.detach_TBL_PHIEUNHAPXUATs));
			this._TBL_PHIEUTHUCHIs = new EntitySet<TBL_PHIEUTHUCHI>(new Action<TBL_PHIEUTHUCHI>(this.attach_TBL_PHIEUTHUCHIs), new Action<TBL_PHIEUTHUCHI>(this.detach_TBL_PHIEUTHUCHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(50)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOTINH", DbType="NVarChar(4)")]
		public string GIOTINH
		{
			get
			{
				return this._GIOTINH;
			}
			set
			{
				if ((this._GIOTINH != value))
				{
					this.OnGIOTINHChanging(value);
					this.SendPropertyChanging();
					this._GIOTINH = value;
					this.SendPropertyChanged("GIOTINH");
					this.OnGIOTINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(30)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHANVIEN_TBL_HOADON", Storage="_TBL_HOADONs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TBL_HOADON> TBL_HOADONs
		{
			get
			{
				return this._TBL_HOADONs;
			}
			set
			{
				this._TBL_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHANVIEN_TBL_PHIEUNHAPXUAT", Storage="_TBL_PHIEUNHAPXUATs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TBL_PHIEUNHAPXUAT> TBL_PHIEUNHAPXUATs
		{
			get
			{
				return this._TBL_PHIEUNHAPXUATs;
			}
			set
			{
				this._TBL_PHIEUNHAPXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHANVIEN_TBL_PHIEUTHUCHI", Storage="_TBL_PHIEUTHUCHIs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TBL_PHIEUTHUCHI> TBL_PHIEUTHUCHIs
		{
			get
			{
				return this._TBL_PHIEUTHUCHIs;
			}
			set
			{
				this._TBL_PHIEUTHUCHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_HOADONs(TBL_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHANVIEN = this;
		}
		
		private void detach_TBL_HOADONs(TBL_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHANVIEN = null;
		}
		
		private void attach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHANVIEN = this;
		}
		
		private void detach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHANVIEN = null;
		}
		
		private void attach_TBL_PHIEUTHUCHIs(TBL_PHIEUTHUCHI entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHANVIEN = this;
		}
		
		private void detach_TBL_PHIEUTHUCHIs(TBL_PHIEUTHUCHI entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NHAXUATBAN")]
	public partial class TBL_NHAXUATBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANXB;
		
		private string _TENNHAXB;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private EntitySet<TBL_PHIEUNHAPXUAT> _TBL_PHIEUNHAPXUATs;
		
		private EntitySet<TBL_SACH> _TBL_SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnTENNHAXBChanging(string value);
    partial void OnTENNHAXBChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public TBL_NHAXUATBAN()
		{
			this._TBL_PHIEUNHAPXUATs = new EntitySet<TBL_PHIEUNHAPXUAT>(new Action<TBL_PHIEUNHAPXUAT>(this.attach_TBL_PHIEUNHAPXUATs), new Action<TBL_PHIEUNHAPXUAT>(this.detach_TBL_PHIEUNHAPXUATs));
			this._TBL_SACHes = new EntitySet<TBL_SACH>(new Action<TBL_SACH>(this.attach_TBL_SACHes), new Action<TBL_SACH>(this.detach_TBL_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHAXB", DbType="NVarChar(50)")]
		public string TENNHAXB
		{
			get
			{
				return this._TENNHAXB;
			}
			set
			{
				if ((this._TENNHAXB != value))
				{
					this.OnTENNHAXBChanging(value);
					this.SendPropertyChanging();
					this._TENNHAXB = value;
					this.SendPropertyChanged("TENNHAXB");
					this.OnTENNHAXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHAXUATBAN_TBL_PHIEUNHAPXUAT", Storage="_TBL_PHIEUNHAPXUATs", ThisKey="MANXB", OtherKey="MANXB")]
		public EntitySet<TBL_PHIEUNHAPXUAT> TBL_PHIEUNHAPXUATs
		{
			get
			{
				return this._TBL_PHIEUNHAPXUATs;
			}
			set
			{
				this._TBL_PHIEUNHAPXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHAXUATBAN_TBL_SACH", Storage="_TBL_SACHes", ThisKey="MANXB", OtherKey="MANXB")]
		public EntitySet<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this._TBL_SACHes;
			}
			set
			{
				this._TBL_SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHAXUATBAN = this;
		}
		
		private void detach_TBL_PHIEUNHAPXUATs(TBL_PHIEUNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHAXUATBAN = null;
		}
		
		private void attach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHAXUATBAN = this;
		}
		
		private void detach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_NHAXUATBAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PHANQUYEN")]
	public partial class TBL_PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHANQUYEN;
		
		private string _QUYEN;
		
		private EntitySet<TBL_USER> _TBL_USERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHANQUYENChanging(string value);
    partial void OnMAPHANQUYENChanged();
    partial void OnQUYENChanging(string value);
    partial void OnQUYENChanged();
    #endregion
		
		public TBL_PHANQUYEN()
		{
			this._TBL_USERs = new EntitySet<TBL_USER>(new Action<TBL_USER>(this.attach_TBL_USERs), new Action<TBL_USER>(this.detach_TBL_USERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHANQUYEN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHANQUYEN
		{
			get
			{
				return this._MAPHANQUYEN;
			}
			set
			{
				if ((this._MAPHANQUYEN != value))
				{
					this.OnMAPHANQUYENChanging(value);
					this.SendPropertyChanging();
					this._MAPHANQUYEN = value;
					this.SendPropertyChanged("MAPHANQUYEN");
					this.OnMAPHANQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="NVarChar(30)")]
		public string QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PHANQUYEN_TBL_USER", Storage="_TBL_USERs", ThisKey="MAPHANQUYEN", OtherKey="MAPHANQUYEN")]
		public EntitySet<TBL_USER> TBL_USERs
		{
			get
			{
				return this._TBL_USERs;
			}
			set
			{
				this._TBL_USERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_USERs(TBL_USER entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PHANQUYEN = this;
		}
		
		private void detach_TBL_USERs(TBL_USER entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PHANQUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PHIEUCTNHAPXUAT")]
	public partial class TBL_PHIEUCTNHAPXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUNX;
		
		private string _MASACH;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<decimal> _DONGIA;
		
		private string _DVT;
		
		private System.Nullable<decimal> _THANHTIEN;
		
		private EntityRef<TBL_PHIEUNHAPXUAT> _TBL_PHIEUNHAPXUAT;
		
		private EntityRef<TBL_SACH> _TBL_SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUNXChanging(string value);
    partial void OnMAPHIEUNXChanged();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnTHANHTIENChanging(System.Nullable<decimal> value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public TBL_PHIEUCTNHAPXUAT()
		{
			this._TBL_PHIEUNHAPXUAT = default(EntityRef<TBL_PHIEUNHAPXUAT>);
			this._TBL_SACH = default(EntityRef<TBL_SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUNX", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUNX
		{
			get
			{
				return this._MAPHIEUNX;
			}
			set
			{
				if ((this._MAPHIEUNX != value))
				{
					if (this._TBL_PHIEUNHAPXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHIEUNXChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUNX = value;
					this.SendPropertyChanged("MAPHIEUNX");
					this.OnMAPHIEUNXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					if (this._TBL_SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Money")]
		public System.Nullable<decimal> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PHIEUNHAPXUAT_TBL_PHIEUCTNHAPXUAT", Storage="_TBL_PHIEUNHAPXUAT", ThisKey="MAPHIEUNX", OtherKey="MAPHIEUNX", IsForeignKey=true)]
		public TBL_PHIEUNHAPXUAT TBL_PHIEUNHAPXUAT
		{
			get
			{
				return this._TBL_PHIEUNHAPXUAT.Entity;
			}
			set
			{
				TBL_PHIEUNHAPXUAT previousValue = this._TBL_PHIEUNHAPXUAT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PHIEUNHAPXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PHIEUNHAPXUAT.Entity = null;
						previousValue.TBL_PHIEUCTNHAPXUATs.Remove(this);
					}
					this._TBL_PHIEUNHAPXUAT.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUCTNHAPXUATs.Add(this);
						this._MAPHIEUNX = value.MAPHIEUNX;
					}
					else
					{
						this._MAPHIEUNX = default(string);
					}
					this.SendPropertyChanged("TBL_PHIEUNHAPXUAT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_SACH_TBL_PHIEUCTNHAPXUAT", Storage="_TBL_SACH", ThisKey="MASACH", OtherKey="MASACH", IsForeignKey=true)]
		public TBL_SACH TBL_SACH
		{
			get
			{
				return this._TBL_SACH.Entity;
			}
			set
			{
				TBL_SACH previousValue = this._TBL_SACH.Entity;
				if (((previousValue != value) 
							|| (this._TBL_SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_SACH.Entity = null;
						previousValue.TBL_PHIEUCTNHAPXUATs.Remove(this);
					}
					this._TBL_SACH.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUCTNHAPXUATs.Add(this);
						this._MASACH = value.MASACH;
					}
					else
					{
						this._MASACH = default(string);
					}
					this.SendPropertyChanged("TBL_SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PHIEUNHAPXUAT")]
	public partial class TBL_PHIEUNHAPXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUNX;
		
		private string _MALOAIPHIEU;
		
		private System.Nullable<System.DateTime> _NGAYNHAPXUAT;
		
		private string _MANXB;
		
		private string _MANV;
		
		private string _MAKHO;
		
		private System.Nullable<decimal> _TRIGIA;
		
		private EntitySet<TBL_PHIEUCTNHAPXUAT> _TBL_PHIEUCTNHAPXUATs;
		
		private EntityRef<TBL_KHO> _TBL_KHO;
		
		private EntityRef<TBL_LOAIPHIEU> _TBL_LOAIPHIEU;
		
		private EntityRef<TBL_NHANVIEN> _TBL_NHANVIEN;
		
		private EntityRef<TBL_NHAXUATBAN> _TBL_NHAXUATBAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUNXChanging(string value);
    partial void OnMAPHIEUNXChanged();
    partial void OnMALOAIPHIEUChanging(string value);
    partial void OnMALOAIPHIEUChanged();
    partial void OnNGAYNHAPXUATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPXUATChanged();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMAKHOChanging(string value);
    partial void OnMAKHOChanged();
    partial void OnTRIGIAChanging(System.Nullable<decimal> value);
    partial void OnTRIGIAChanged();
    #endregion
		
		public TBL_PHIEUNHAPXUAT()
		{
			this._TBL_PHIEUCTNHAPXUATs = new EntitySet<TBL_PHIEUCTNHAPXUAT>(new Action<TBL_PHIEUCTNHAPXUAT>(this.attach_TBL_PHIEUCTNHAPXUATs), new Action<TBL_PHIEUCTNHAPXUAT>(this.detach_TBL_PHIEUCTNHAPXUATs));
			this._TBL_KHO = default(EntityRef<TBL_KHO>);
			this._TBL_LOAIPHIEU = default(EntityRef<TBL_LOAIPHIEU>);
			this._TBL_NHANVIEN = default(EntityRef<TBL_NHANVIEN>);
			this._TBL_NHAXUATBAN = default(EntityRef<TBL_NHAXUATBAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUNX", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUNX
		{
			get
			{
				return this._MAPHIEUNX;
			}
			set
			{
				if ((this._MAPHIEUNX != value))
				{
					this.OnMAPHIEUNXChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUNX = value;
					this.SendPropertyChanged("MAPHIEUNX");
					this.OnMAPHIEUNXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIPHIEU", DbType="NChar(10)")]
		public string MALOAIPHIEU
		{
			get
			{
				return this._MALOAIPHIEU;
			}
			set
			{
				if ((this._MALOAIPHIEU != value))
				{
					if (this._TBL_LOAIPHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MALOAIPHIEU = value;
					this.SendPropertyChanged("MALOAIPHIEU");
					this.OnMALOAIPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAPXUAT", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHAPXUAT
		{
			get
			{
				return this._NGAYNHAPXUAT;
			}
			set
			{
				if ((this._NGAYNHAPXUAT != value))
				{
					this.OnNGAYNHAPXUATChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAPXUAT = value;
					this.SendPropertyChanged("NGAYNHAPXUAT");
					this.OnNGAYNHAPXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="NChar(10)")]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					if (this._TBL_NHAXUATBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NChar(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._TBL_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHO", DbType="NChar(10)")]
		public string MAKHO
		{
			get
			{
				return this._MAKHO;
			}
			set
			{
				if ((this._MAKHO != value))
				{
					if (this._TBL_KHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHOChanging(value);
					this.SendPropertyChanging();
					this._MAKHO = value;
					this.SendPropertyChanged("MAKHO");
					this.OnMAKHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGIA", DbType="Money")]
		public System.Nullable<decimal> TRIGIA
		{
			get
			{
				return this._TRIGIA;
			}
			set
			{
				if ((this._TRIGIA != value))
				{
					this.OnTRIGIAChanging(value);
					this.SendPropertyChanging();
					this._TRIGIA = value;
					this.SendPropertyChanged("TRIGIA");
					this.OnTRIGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PHIEUNHAPXUAT_TBL_PHIEUCTNHAPXUAT", Storage="_TBL_PHIEUCTNHAPXUATs", ThisKey="MAPHIEUNX", OtherKey="MAPHIEUNX")]
		public EntitySet<TBL_PHIEUCTNHAPXUAT> TBL_PHIEUCTNHAPXUATs
		{
			get
			{
				return this._TBL_PHIEUCTNHAPXUATs;
			}
			set
			{
				this._TBL_PHIEUCTNHAPXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_KHO_TBL_PHIEUNHAPXUAT", Storage="_TBL_KHO", ThisKey="MAKHO", OtherKey="MAKHO", IsForeignKey=true)]
		public TBL_KHO TBL_KHO
		{
			get
			{
				return this._TBL_KHO.Entity;
			}
			set
			{
				TBL_KHO previousValue = this._TBL_KHO.Entity;
				if (((previousValue != value) 
							|| (this._TBL_KHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_KHO.Entity = null;
						previousValue.TBL_PHIEUNHAPXUATs.Remove(this);
					}
					this._TBL_KHO.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUNHAPXUATs.Add(this);
						this._MAKHO = value.MAKHO;
					}
					else
					{
						this._MAKHO = default(string);
					}
					this.SendPropertyChanged("TBL_KHO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_LOAIPHIEU_TBL_PHIEUNHAPXUAT", Storage="_TBL_LOAIPHIEU", ThisKey="MALOAIPHIEU", OtherKey="MALOAIPHIEU", IsForeignKey=true)]
		public TBL_LOAIPHIEU TBL_LOAIPHIEU
		{
			get
			{
				return this._TBL_LOAIPHIEU.Entity;
			}
			set
			{
				TBL_LOAIPHIEU previousValue = this._TBL_LOAIPHIEU.Entity;
				if (((previousValue != value) 
							|| (this._TBL_LOAIPHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_LOAIPHIEU.Entity = null;
						previousValue.TBL_PHIEUNHAPXUATs.Remove(this);
					}
					this._TBL_LOAIPHIEU.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUNHAPXUATs.Add(this);
						this._MALOAIPHIEU = value.MALOAIPHIEU;
					}
					else
					{
						this._MALOAIPHIEU = default(string);
					}
					this.SendPropertyChanged("TBL_LOAIPHIEU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHANVIEN_TBL_PHIEUNHAPXUAT", Storage="_TBL_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public TBL_NHANVIEN TBL_NHANVIEN
		{
			get
			{
				return this._TBL_NHANVIEN.Entity;
			}
			set
			{
				TBL_NHANVIEN previousValue = this._TBL_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._TBL_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_NHANVIEN.Entity = null;
						previousValue.TBL_PHIEUNHAPXUATs.Remove(this);
					}
					this._TBL_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUNHAPXUATs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("TBL_NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHAXUATBAN_TBL_PHIEUNHAPXUAT", Storage="_TBL_NHAXUATBAN", ThisKey="MANXB", OtherKey="MANXB", IsForeignKey=true)]
		public TBL_NHAXUATBAN TBL_NHAXUATBAN
		{
			get
			{
				return this._TBL_NHAXUATBAN.Entity;
			}
			set
			{
				TBL_NHAXUATBAN previousValue = this._TBL_NHAXUATBAN.Entity;
				if (((previousValue != value) 
							|| (this._TBL_NHAXUATBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_NHAXUATBAN.Entity = null;
						previousValue.TBL_PHIEUNHAPXUATs.Remove(this);
					}
					this._TBL_NHAXUATBAN.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUNHAPXUATs.Add(this);
						this._MANXB = value.MANXB;
					}
					else
					{
						this._MANXB = default(string);
					}
					this.SendPropertyChanged("TBL_NHAXUATBAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PHIEUCTNHAPXUATs(TBL_PHIEUCTNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PHIEUNHAPXUAT = this;
		}
		
		private void detach_TBL_PHIEUCTNHAPXUATs(TBL_PHIEUCTNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PHIEUNHAPXUAT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PHIEUTHUCHI")]
	public partial class TBL_PHIEUTHUCHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUTC;
		
		private string _MALOAIPHIEU;
		
		private System.Nullable<System.DateTime> _NGAYTHUCHI;
		
		private string _MANV;
		
		private string _MAKHACH;
		
		private string _LIDO;
		
		private System.Nullable<decimal> _TRIGIA;
		
		private EntityRef<TBL_KHACHHANG> _TBL_KHACHHANG;
		
		private EntityRef<TBL_LOAIPHIEU> _TBL_LOAIPHIEU;
		
		private EntityRef<TBL_NHANVIEN> _TBL_NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUTCChanging(string value);
    partial void OnMAPHIEUTCChanged();
    partial void OnMALOAIPHIEUChanging(string value);
    partial void OnMALOAIPHIEUChanged();
    partial void OnNGAYTHUCHIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHUCHIChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMAKHACHChanging(string value);
    partial void OnMAKHACHChanged();
    partial void OnLIDOChanging(string value);
    partial void OnLIDOChanged();
    partial void OnTRIGIAChanging(System.Nullable<decimal> value);
    partial void OnTRIGIAChanged();
    #endregion
		
		public TBL_PHIEUTHUCHI()
		{
			this._TBL_KHACHHANG = default(EntityRef<TBL_KHACHHANG>);
			this._TBL_LOAIPHIEU = default(EntityRef<TBL_LOAIPHIEU>);
			this._TBL_NHANVIEN = default(EntityRef<TBL_NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUTC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUTC
		{
			get
			{
				return this._MAPHIEUTC;
			}
			set
			{
				if ((this._MAPHIEUTC != value))
				{
					this.OnMAPHIEUTCChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUTC = value;
					this.SendPropertyChanged("MAPHIEUTC");
					this.OnMAPHIEUTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIPHIEU", DbType="NChar(10)")]
		public string MALOAIPHIEU
		{
			get
			{
				return this._MALOAIPHIEU;
			}
			set
			{
				if ((this._MALOAIPHIEU != value))
				{
					if (this._TBL_LOAIPHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MALOAIPHIEU = value;
					this.SendPropertyChanged("MALOAIPHIEU");
					this.OnMALOAIPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHUCHI", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTHUCHI
		{
			get
			{
				return this._NGAYTHUCHI;
			}
			set
			{
				if ((this._NGAYTHUCHI != value))
				{
					this.OnNGAYTHUCHIChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHUCHI = value;
					this.SendPropertyChanged("NGAYTHUCHI");
					this.OnNGAYTHUCHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NChar(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._TBL_NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACH", DbType="NChar(10)")]
		public string MAKHACH
		{
			get
			{
				return this._MAKHACH;
			}
			set
			{
				if ((this._MAKHACH != value))
				{
					if (this._TBL_KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHACHChanging(value);
					this.SendPropertyChanging();
					this._MAKHACH = value;
					this.SendPropertyChanged("MAKHACH");
					this.OnMAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIDO", DbType="NVarChar(500)")]
		public string LIDO
		{
			get
			{
				return this._LIDO;
			}
			set
			{
				if ((this._LIDO != value))
				{
					this.OnLIDOChanging(value);
					this.SendPropertyChanging();
					this._LIDO = value;
					this.SendPropertyChanged("LIDO");
					this.OnLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRIGIA", DbType="Money")]
		public System.Nullable<decimal> TRIGIA
		{
			get
			{
				return this._TRIGIA;
			}
			set
			{
				if ((this._TRIGIA != value))
				{
					this.OnTRIGIAChanging(value);
					this.SendPropertyChanging();
					this._TRIGIA = value;
					this.SendPropertyChanged("TRIGIA");
					this.OnTRIGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_KHACHHANG_TBL_PHIEUTHUCHI", Storage="_TBL_KHACHHANG", ThisKey="MAKHACH", OtherKey="MAKH", IsForeignKey=true)]
		public TBL_KHACHHANG TBL_KHACHHANG
		{
			get
			{
				return this._TBL_KHACHHANG.Entity;
			}
			set
			{
				TBL_KHACHHANG previousValue = this._TBL_KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._TBL_KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_KHACHHANG.Entity = null;
						previousValue.TBL_PHIEUTHUCHIs.Remove(this);
					}
					this._TBL_KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUTHUCHIs.Add(this);
						this._MAKHACH = value.MAKH;
					}
					else
					{
						this._MAKHACH = default(string);
					}
					this.SendPropertyChanged("TBL_KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_LOAIPHIEU_TBL_PHIEUTHUCHI", Storage="_TBL_LOAIPHIEU", ThisKey="MALOAIPHIEU", OtherKey="MALOAIPHIEU", IsForeignKey=true)]
		public TBL_LOAIPHIEU TBL_LOAIPHIEU
		{
			get
			{
				return this._TBL_LOAIPHIEU.Entity;
			}
			set
			{
				TBL_LOAIPHIEU previousValue = this._TBL_LOAIPHIEU.Entity;
				if (((previousValue != value) 
							|| (this._TBL_LOAIPHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_LOAIPHIEU.Entity = null;
						previousValue.TBL_PHIEUTHUCHIs.Remove(this);
					}
					this._TBL_LOAIPHIEU.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUTHUCHIs.Add(this);
						this._MALOAIPHIEU = value.MALOAIPHIEU;
					}
					else
					{
						this._MALOAIPHIEU = default(string);
					}
					this.SendPropertyChanged("TBL_LOAIPHIEU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHANVIEN_TBL_PHIEUTHUCHI", Storage="_TBL_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public TBL_NHANVIEN TBL_NHANVIEN
		{
			get
			{
				return this._TBL_NHANVIEN.Entity;
			}
			set
			{
				TBL_NHANVIEN previousValue = this._TBL_NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._TBL_NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_NHANVIEN.Entity = null;
						previousValue.TBL_PHIEUTHUCHIs.Remove(this);
					}
					this._TBL_NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TBL_PHIEUTHUCHIs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("TBL_NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_SACH")]
	public partial class TBL_SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASACH;
		
		private string _TENSACH;
		
		private string _ANH;
		
		private string _MATACGIA;
		
		private string _MANXB;
		
		private string _MATHELOAI;
		
		private System.Nullable<decimal> _DONGIA;
		
		private string _DVT;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<int> _SOLUONGTON;
		
		private string _MOTA;
		
		private EntitySet<TBL_CTHOADON> _TBL_CTHOADONs;
		
		private EntitySet<TBL_PHIEUCTNHAPXUAT> _TBL_PHIEUCTNHAPXUATs;
		
		private EntityRef<TBL_NHAXUATBAN> _TBL_NHAXUATBAN;
		
		private EntityRef<TBL_TACGIA> _TBL_TACGIA;
		
		private EntityRef<TBL_THELOAI> _TBL_THELOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASACHChanging(string value);
    partial void OnMASACHChanged();
    partial void OnTENSACHChanging(string value);
    partial void OnTENSACHChanged();
    partial void OnANHChanging(string value);
    partial void OnANHChanged();
    partial void OnMATACGIAChanging(string value);
    partial void OnMATACGIAChanged();
    partial void OnMANXBChanging(string value);
    partial void OnMANXBChanged();
    partial void OnMATHELOAIChanging(string value);
    partial void OnMATHELOAIChanged();
    partial void OnDONGIAChanging(System.Nullable<decimal> value);
    partial void OnDONGIAChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnSOLUONGTONChanging(System.Nullable<int> value);
    partial void OnSOLUONGTONChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    #endregion
		
		public TBL_SACH()
		{
			this._TBL_CTHOADONs = new EntitySet<TBL_CTHOADON>(new Action<TBL_CTHOADON>(this.attach_TBL_CTHOADONs), new Action<TBL_CTHOADON>(this.detach_TBL_CTHOADONs));
			this._TBL_PHIEUCTNHAPXUATs = new EntitySet<TBL_PHIEUCTNHAPXUAT>(new Action<TBL_PHIEUCTNHAPXUAT>(this.attach_TBL_PHIEUCTNHAPXUATs), new Action<TBL_PHIEUCTNHAPXUAT>(this.detach_TBL_PHIEUCTNHAPXUATs));
			this._TBL_NHAXUATBAN = default(EntityRef<TBL_NHAXUATBAN>);
			this._TBL_TACGIA = default(EntityRef<TBL_TACGIA>);
			this._TBL_THELOAI = default(EntityRef<TBL_THELOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASACH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASACH
		{
			get
			{
				return this._MASACH;
			}
			set
			{
				if ((this._MASACH != value))
				{
					this.OnMASACHChanging(value);
					this.SendPropertyChanging();
					this._MASACH = value;
					this.SendPropertyChanged("MASACH");
					this.OnMASACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSACH", DbType="NVarChar(50)")]
		public string TENSACH
		{
			get
			{
				return this._TENSACH;
			}
			set
			{
				if ((this._TENSACH != value))
				{
					this.OnTENSACHChanging(value);
					this.SendPropertyChanging();
					this._TENSACH = value;
					this.SendPropertyChanged("TENSACH");
					this.OnTENSACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH", DbType="VarChar(50)")]
		public string ANH
		{
			get
			{
				return this._ANH;
			}
			set
			{
				if ((this._ANH != value))
				{
					this.OnANHChanging(value);
					this.SendPropertyChanging();
					this._ANH = value;
					this.SendPropertyChanged("ANH");
					this.OnANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATACGIA", DbType="NChar(10)")]
		public string MATACGIA
		{
			get
			{
				return this._MATACGIA;
			}
			set
			{
				if ((this._MATACGIA != value))
				{
					if (this._TBL_TACGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATACGIAChanging(value);
					this.SendPropertyChanging();
					this._MATACGIA = value;
					this.SendPropertyChanged("MATACGIA");
					this.OnMATACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANXB", DbType="NChar(10)")]
		public string MANXB
		{
			get
			{
				return this._MANXB;
			}
			set
			{
				if ((this._MANXB != value))
				{
					if (this._TBL_NHAXUATBAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANXBChanging(value);
					this.SendPropertyChanging();
					this._MANXB = value;
					this.SendPropertyChanged("MANXB");
					this.OnMANXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHELOAI", DbType="NChar(10)")]
		public string MATHELOAI
		{
			get
			{
				return this._MATHELOAI;
			}
			set
			{
				if ((this._MATHELOAI != value))
				{
					if (this._TBL_THELOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHELOAIChanging(value);
					this.SendPropertyChanging();
					this._MATHELOAI = value;
					this.SendPropertyChanged("MATHELOAI");
					this.OnMATHELOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Money")]
		public System.Nullable<decimal> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGTON", DbType="Int")]
		public System.Nullable<int> SOLUONGTON
		{
			get
			{
				return this._SOLUONGTON;
			}
			set
			{
				if ((this._SOLUONGTON != value))
				{
					this.OnSOLUONGTONChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGTON = value;
					this.SendPropertyChanged("SOLUONGTON");
					this.OnSOLUONGTONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(1000)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_SACH_TBL_CTHOADON", Storage="_TBL_CTHOADONs", ThisKey="MASACH", OtherKey="MASACH")]
		public EntitySet<TBL_CTHOADON> TBL_CTHOADONs
		{
			get
			{
				return this._TBL_CTHOADONs;
			}
			set
			{
				this._TBL_CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_SACH_TBL_PHIEUCTNHAPXUAT", Storage="_TBL_PHIEUCTNHAPXUATs", ThisKey="MASACH", OtherKey="MASACH")]
		public EntitySet<TBL_PHIEUCTNHAPXUAT> TBL_PHIEUCTNHAPXUATs
		{
			get
			{
				return this._TBL_PHIEUCTNHAPXUATs;
			}
			set
			{
				this._TBL_PHIEUCTNHAPXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_NHAXUATBAN_TBL_SACH", Storage="_TBL_NHAXUATBAN", ThisKey="MANXB", OtherKey="MANXB", IsForeignKey=true)]
		public TBL_NHAXUATBAN TBL_NHAXUATBAN
		{
			get
			{
				return this._TBL_NHAXUATBAN.Entity;
			}
			set
			{
				TBL_NHAXUATBAN previousValue = this._TBL_NHAXUATBAN.Entity;
				if (((previousValue != value) 
							|| (this._TBL_NHAXUATBAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_NHAXUATBAN.Entity = null;
						previousValue.TBL_SACHes.Remove(this);
					}
					this._TBL_NHAXUATBAN.Entity = value;
					if ((value != null))
					{
						value.TBL_SACHes.Add(this);
						this._MANXB = value.MANXB;
					}
					else
					{
						this._MANXB = default(string);
					}
					this.SendPropertyChanged("TBL_NHAXUATBAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_TACGIA_TBL_SACH", Storage="_TBL_TACGIA", ThisKey="MATACGIA", OtherKey="MATACGIA", IsForeignKey=true)]
		public TBL_TACGIA TBL_TACGIA
		{
			get
			{
				return this._TBL_TACGIA.Entity;
			}
			set
			{
				TBL_TACGIA previousValue = this._TBL_TACGIA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_TACGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_TACGIA.Entity = null;
						previousValue.TBL_SACHes.Remove(this);
					}
					this._TBL_TACGIA.Entity = value;
					if ((value != null))
					{
						value.TBL_SACHes.Add(this);
						this._MATACGIA = value.MATACGIA;
					}
					else
					{
						this._MATACGIA = default(string);
					}
					this.SendPropertyChanged("TBL_TACGIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_THELOAI_TBL_SACH", Storage="_TBL_THELOAI", ThisKey="MATHELOAI", OtherKey="MATHELOAI", IsForeignKey=true)]
		public TBL_THELOAI TBL_THELOAI
		{
			get
			{
				return this._TBL_THELOAI.Entity;
			}
			set
			{
				TBL_THELOAI previousValue = this._TBL_THELOAI.Entity;
				if (((previousValue != value) 
							|| (this._TBL_THELOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_THELOAI.Entity = null;
						previousValue.TBL_SACHes.Remove(this);
					}
					this._TBL_THELOAI.Entity = value;
					if ((value != null))
					{
						value.TBL_SACHes.Add(this);
						this._MATHELOAI = value.MATHELOAI;
					}
					else
					{
						this._MATHELOAI = default(string);
					}
					this.SendPropertyChanged("TBL_THELOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_CTHOADONs(TBL_CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_SACH = this;
		}
		
		private void detach_TBL_CTHOADONs(TBL_CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.TBL_SACH = null;
		}
		
		private void attach_TBL_PHIEUCTNHAPXUATs(TBL_PHIEUCTNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_SACH = this;
		}
		
		private void detach_TBL_PHIEUCTNHAPXUATs(TBL_PHIEUCTNHAPXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_SACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_SODOANHTHU")]
	public partial class TBL_SODOANHTHU
	{
		
		private System.Nullable<System.DateTime> _NGAY;
		
		private System.Nullable<decimal> _TIENTONDAUKY;
		
		private System.Nullable<decimal> _THU;
		
		private System.Nullable<decimal> _CHI;
		
		private System.Nullable<decimal> _TIENTONCUOIKY;
		
		public TBL_SODOANHTHU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY", DbType="Date")]
		public System.Nullable<System.DateTime> NGAY
		{
			get
			{
				return this._NGAY;
			}
			set
			{
				if ((this._NGAY != value))
				{
					this._NGAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENTONDAUKY", DbType="Money")]
		public System.Nullable<decimal> TIENTONDAUKY
		{
			get
			{
				return this._TIENTONDAUKY;
			}
			set
			{
				if ((this._TIENTONDAUKY != value))
				{
					this._TIENTONDAUKY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THU", DbType="Money")]
		public System.Nullable<decimal> THU
		{
			get
			{
				return this._THU;
			}
			set
			{
				if ((this._THU != value))
				{
					this._THU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHI", DbType="Money")]
		public System.Nullable<decimal> CHI
		{
			get
			{
				return this._CHI;
			}
			set
			{
				if ((this._CHI != value))
				{
					this._CHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENTONCUOIKY", DbType="Money")]
		public System.Nullable<decimal> TIENTONCUOIKY
		{
			get
			{
				return this._TIENTONCUOIKY;
			}
			set
			{
				if ((this._TIENTONCUOIKY != value))
				{
					this._TIENTONCUOIKY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_TACGIA")]
	public partial class TBL_TACGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATACGIA;
		
		private string _TENTACGIA;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private EntitySet<TBL_SACH> _TBL_SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATACGIAChanging(string value);
    partial void OnMATACGIAChanged();
    partial void OnTENTACGIAChanging(string value);
    partial void OnTENTACGIAChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public TBL_TACGIA()
		{
			this._TBL_SACHes = new EntitySet<TBL_SACH>(new Action<TBL_SACH>(this.attach_TBL_SACHes), new Action<TBL_SACH>(this.detach_TBL_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATACGIA", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATACGIA
		{
			get
			{
				return this._MATACGIA;
			}
			set
			{
				if ((this._MATACGIA != value))
				{
					this.OnMATACGIAChanging(value);
					this.SendPropertyChanging();
					this._MATACGIA = value;
					this.SendPropertyChanged("MATACGIA");
					this.OnMATACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTACGIA", DbType="NVarChar(50)")]
		public string TENTACGIA
		{
			get
			{
				return this._TENTACGIA;
			}
			set
			{
				if ((this._TENTACGIA != value))
				{
					this.OnTENTACGIAChanging(value);
					this.SendPropertyChanging();
					this._TENTACGIA = value;
					this.SendPropertyChanged("TENTACGIA");
					this.OnTENTACGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_TACGIA_TBL_SACH", Storage="_TBL_SACHes", ThisKey="MATACGIA", OtherKey="MATACGIA")]
		public EntitySet<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this._TBL_SACHes;
			}
			set
			{
				this._TBL_SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_TACGIA = this;
		}
		
		private void detach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_TACGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_THELOAI")]
	public partial class TBL_THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHELOAI;
		
		private string _TENTHELOAI;
		
		private EntitySet<TBL_SACH> _TBL_SACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHELOAIChanging(string value);
    partial void OnMATHELOAIChanged();
    partial void OnTENTHELOAIChanging(string value);
    partial void OnTENTHELOAIChanged();
    #endregion
		
		public TBL_THELOAI()
		{
			this._TBL_SACHes = new EntitySet<TBL_SACH>(new Action<TBL_SACH>(this.attach_TBL_SACHes), new Action<TBL_SACH>(this.detach_TBL_SACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHELOAI", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHELOAI
		{
			get
			{
				return this._MATHELOAI;
			}
			set
			{
				if ((this._MATHELOAI != value))
				{
					this.OnMATHELOAIChanging(value);
					this.SendPropertyChanging();
					this._MATHELOAI = value;
					this.SendPropertyChanged("MATHELOAI");
					this.OnMATHELOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHELOAI", DbType="NVarChar(50)")]
		public string TENTHELOAI
		{
			get
			{
				return this._TENTHELOAI;
			}
			set
			{
				if ((this._TENTHELOAI != value))
				{
					this.OnTENTHELOAIChanging(value);
					this.SendPropertyChanging();
					this._TENTHELOAI = value;
					this.SendPropertyChanged("TENTHELOAI");
					this.OnTENTHELOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_THELOAI_TBL_SACH", Storage="_TBL_SACHes", ThisKey="MATHELOAI", OtherKey="MATHELOAI")]
		public EntitySet<TBL_SACH> TBL_SACHes
		{
			get
			{
				return this._TBL_SACHes;
			}
			set
			{
				this._TBL_SACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_THELOAI = this;
		}
		
		private void detach_TBL_SACHes(TBL_SACH entity)
		{
			this.SendPropertyChanging();
			entity.TBL_THELOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USER")]
	public partial class TBL_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERID;
		
		private string _NAME;
		
		private string _PW;
		
		private string _MAPHANQUYEN;
		
		private EntityRef<TBL_PHANQUYEN> _TBL_PHANQUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERIDChanging(string value);
    partial void OnUSERIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnMAPHANQUYENChanging(string value);
    partial void OnMAPHANQUYENChanged();
    #endregion
		
		public TBL_USER()
		{
			this._TBL_PHANQUYEN = default(EntityRef<TBL_PHANQUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this.OnUSERIDChanging(value);
					this.SendPropertyChanging();
					this._USERID = value;
					this.SendPropertyChanged("USERID");
					this.OnUSERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(30)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="NChar(30)")]
		public string PW
		{
			get
			{
				return this._PW;
			}
			set
			{
				if ((this._PW != value))
				{
					this.OnPWChanging(value);
					this.SendPropertyChanging();
					this._PW = value;
					this.SendPropertyChanged("PW");
					this.OnPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHANQUYEN", DbType="NChar(10)")]
		public string MAPHANQUYEN
		{
			get
			{
				return this._MAPHANQUYEN;
			}
			set
			{
				if ((this._MAPHANQUYEN != value))
				{
					if (this._TBL_PHANQUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHANQUYENChanging(value);
					this.SendPropertyChanging();
					this._MAPHANQUYEN = value;
					this.SendPropertyChanged("MAPHANQUYEN");
					this.OnMAPHANQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PHANQUYEN_TBL_USER", Storage="_TBL_PHANQUYEN", ThisKey="MAPHANQUYEN", OtherKey="MAPHANQUYEN", IsForeignKey=true)]
		public TBL_PHANQUYEN TBL_PHANQUYEN
		{
			get
			{
				return this._TBL_PHANQUYEN.Entity;
			}
			set
			{
				TBL_PHANQUYEN previousValue = this._TBL_PHANQUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PHANQUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PHANQUYEN.Entity = null;
						previousValue.TBL_USERs.Remove(this);
					}
					this._TBL_PHANQUYEN.Entity = value;
					if ((value != null))
					{
						value.TBL_USERs.Add(this);
						this._MAPHANQUYEN = value.MAPHANQUYEN;
					}
					else
					{
						this._MAPHANQUYEN = default(string);
					}
					this.SendPropertyChanged("TBL_PHANQUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
