<?xml version="1.0" encoding="utf-8"?><Database Name="QLNhaSach" Class="QLNhaSachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-7JOC3DO;Initial Catalog=QLNhaSach;User ID=sa" SettingsObjectName="QLNhaSach.Properties.Settings" SettingsPropertyName="QLNhaSachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_CTHOADON" Member="TBL_CTHOADONs">
    <Type Name="TBL_CTHOADON">
      <Column Name="MAHOADON" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASACH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="TBL_HOADON_TBL_CTHOADON" Member="TBL_HOADON" ThisKey="MAHOADON" OtherKey="MAHOADON" Type="TBL_HOADON" IsForeignKey="true" />
      <Association Name="TBL_SACH_TBL_CTHOADON" Member="TBL_SACH" ThisKey="MASACH" OtherKey="MASACH" Type="TBL_SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_HOADON" Member="TBL_HOADONs">
    <Type Name="TBL_HOADON">
      <Column Name="MAHOADON" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MAKHACH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="TBL_HOADON_TBL_CTHOADON" Member="TBL_CTHOADONs" ThisKey="MAHOADON" OtherKey="MAHOADON" Type="TBL_CTHOADON" />
      <Association Name="TBL_KHACHHANG_TBL_HOADON" Member="TBL_KHACHHANG" ThisKey="MAKHACH" OtherKey="MAKH" Type="TBL_KHACHHANG" IsForeignKey="true" />
      <Association Name="TBL_NHANVIEN_TBL_HOADON" Member="TBL_NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="TBL_NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KHACHHANG" Member="TBL_KHACHHANGs">
    <Type Name="TBL_KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TBL_KHACHHANG_TBL_HOADON" Member="TBL_HOADONs" ThisKey="MAKH" OtherKey="MAKHACH" Type="TBL_HOADON" />
      <Association Name="TBL_KHACHHANG_TBL_PHIEUTHUCHI" Member="TBL_PHIEUTHUCHIs" ThisKey="MAKH" OtherKey="MAKHACH" Type="TBL_PHIEUTHUCHI" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_KHO" Member="TBL_KHOs">
    <Type Name="TBL_KHO">
      <Column Name="MAKHO" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TBL_KHO_TBL_PHIEUNHAPXUAT" Member="TBL_PHIEUNHAPXUATs" ThisKey="MAKHO" OtherKey="MAKHO" Type="TBL_PHIEUNHAPXUAT" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_LOAIPHIEU" Member="TBL_LOAIPHIEUs">
    <Type Name="TBL_LOAIPHIEU">
      <Column Name="MALOAIPHIEU" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIPHIEU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="TBL_LOAIPHIEU_TBL_PHIEUNHAPXUAT" Member="TBL_PHIEUNHAPXUATs" ThisKey="MALOAIPHIEU" OtherKey="MALOAIPHIEU" Type="TBL_PHIEUNHAPXUAT" />
      <Association Name="TBL_LOAIPHIEU_TBL_PHIEUTHUCHI" Member="TBL_PHIEUTHUCHIs" ThisKey="MALOAIPHIEU" OtherKey="MALOAIPHIEU" Type="TBL_PHIEUTHUCHI" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_NHANVIEN" Member="TBL_NHANVIENs">
    <Type Name="TBL_NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOTINH" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="TBL_NHANVIEN_TBL_HOADON" Member="TBL_HOADONs" ThisKey="MANV" OtherKey="MANV" Type="TBL_HOADON" />
      <Association Name="TBL_NHANVIEN_TBL_PHIEUNHAPXUAT" Member="TBL_PHIEUNHAPXUATs" ThisKey="MANV" OtherKey="MANV" Type="TBL_PHIEUNHAPXUAT" />
      <Association Name="TBL_NHANVIEN_TBL_PHIEUTHUCHI" Member="TBL_PHIEUTHUCHIs" ThisKey="MANV" OtherKey="MANV" Type="TBL_PHIEUTHUCHI" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_NHAXUATBAN" Member="TBL_NHAXUATBANs">
    <Type Name="TBL_NHAXUATBAN">
      <Column Name="MANXB" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHAXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TBL_NHAXUATBAN_TBL_PHIEUNHAPXUAT" Member="TBL_PHIEUNHAPXUATs" ThisKey="MANXB" OtherKey="MANXB" Type="TBL_PHIEUNHAPXUAT" />
      <Association Name="TBL_NHAXUATBAN_TBL_SACH" Member="TBL_SACHes" ThisKey="MANXB" OtherKey="MANXB" Type="TBL_SACH" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PHANQUYEN" Member="TBL_PHANQUYENs">
    <Type Name="TBL_PHANQUYEN">
      <Column Name="MAPHANQUYEN" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QUYEN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="TBL_PHANQUYEN_TBL_USER" Member="TBL_USERs" ThisKey="MAPHANQUYEN" OtherKey="MAPHANQUYEN" Type="TBL_USER" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PHIEUCTNHAPXUAT" Member="TBL_PHIEUCTNHAPXUATs">
    <Type Name="TBL_PHIEUCTNHAPXUAT">
      <Column Name="MAPHIEUNX" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASACH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="TBL_PHIEUNHAPXUAT_TBL_PHIEUCTNHAPXUAT" Member="TBL_PHIEUNHAPXUAT" ThisKey="MAPHIEUNX" OtherKey="MAPHIEUNX" Type="TBL_PHIEUNHAPXUAT" IsForeignKey="true" />
      <Association Name="TBL_SACH_TBL_PHIEUCTNHAPXUAT" Member="TBL_SACH" ThisKey="MASACH" OtherKey="MASACH" Type="TBL_SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PHIEUNHAPXUAT" Member="TBL_PHIEUNHAPXUATs">
    <Type Name="TBL_PHIEUNHAPXUAT">
      <Column Name="MAPHIEUNX" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIPHIEU" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NGAYNHAPXUAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANXB" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MAKHO" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TRIGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="TBL_PHIEUNHAPXUAT_TBL_PHIEUCTNHAPXUAT" Member="TBL_PHIEUCTNHAPXUATs" ThisKey="MAPHIEUNX" OtherKey="MAPHIEUNX" Type="TBL_PHIEUCTNHAPXUAT" />
      <Association Name="TBL_KHO_TBL_PHIEUNHAPXUAT" Member="TBL_KHO" ThisKey="MAKHO" OtherKey="MAKHO" Type="TBL_KHO" IsForeignKey="true" />
      <Association Name="TBL_LOAIPHIEU_TBL_PHIEUNHAPXUAT" Member="TBL_LOAIPHIEU" ThisKey="MALOAIPHIEU" OtherKey="MALOAIPHIEU" Type="TBL_LOAIPHIEU" IsForeignKey="true" />
      <Association Name="TBL_NHANVIEN_TBL_PHIEUNHAPXUAT" Member="TBL_NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="TBL_NHANVIEN" IsForeignKey="true" />
      <Association Name="TBL_NHAXUATBAN_TBL_PHIEUNHAPXUAT" Member="TBL_NHAXUATBAN" ThisKey="MANXB" OtherKey="MANXB" Type="TBL_NHAXUATBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PHIEUTHUCHI" Member="TBL_PHIEUTHUCHIs">
    <Type Name="TBL_PHIEUTHUCHI">
      <Column Name="MAPHIEUTC" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIPHIEU" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NGAYTHUCHI" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MAKHACH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LIDO" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TRIGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="TBL_KHACHHANG_TBL_PHIEUTHUCHI" Member="TBL_KHACHHANG" ThisKey="MAKHACH" OtherKey="MAKH" Type="TBL_KHACHHANG" IsForeignKey="true" />
      <Association Name="TBL_LOAIPHIEU_TBL_PHIEUTHUCHI" Member="TBL_LOAIPHIEU" ThisKey="MALOAIPHIEU" OtherKey="MALOAIPHIEU" Type="TBL_LOAIPHIEU" IsForeignKey="true" />
      <Association Name="TBL_NHANVIEN_TBL_PHIEUTHUCHI" Member="TBL_NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="TBL_NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SACH" Member="TBL_SACHes">
    <Type Name="TBL_SACH">
      <Column Name="MASACH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ANH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MATACGIA" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MANXB" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MATHELOAI" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="TBL_SACH_TBL_CTHOADON" Member="TBL_CTHOADONs" ThisKey="MASACH" OtherKey="MASACH" Type="TBL_CTHOADON" />
      <Association Name="TBL_SACH_TBL_PHIEUCTNHAPXUAT" Member="TBL_PHIEUCTNHAPXUATs" ThisKey="MASACH" OtherKey="MASACH" Type="TBL_PHIEUCTNHAPXUAT" />
      <Association Name="TBL_NHAXUATBAN_TBL_SACH" Member="TBL_NHAXUATBAN" ThisKey="MANXB" OtherKey="MANXB" Type="TBL_NHAXUATBAN" IsForeignKey="true" />
      <Association Name="TBL_TACGIA_TBL_SACH" Member="TBL_TACGIA" ThisKey="MATACGIA" OtherKey="MATACGIA" Type="TBL_TACGIA" IsForeignKey="true" />
      <Association Name="TBL_THELOAI_TBL_SACH" Member="TBL_THELOAI" ThisKey="MATHELOAI" OtherKey="MATHELOAI" Type="TBL_THELOAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SODOANHTHU" Member="TBL_SODOANHTHUs">
    <Type Name="TBL_SODOANHTHU">
      <Column Name="NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TIENTONDAUKY" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="THU" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CHI" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TIENTONCUOIKY" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_TACGIA" Member="TBL_TACGIAs">
    <Type Name="TBL_TACGIA">
      <Column Name="MATACGIA" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTACGIA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TBL_TACGIA_TBL_SACH" Member="TBL_SACHes" ThisKey="MATACGIA" OtherKey="MATACGIA" Type="TBL_SACH" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_THELOAI" Member="TBL_THELOAIs">
    <Type Name="TBL_THELOAI">
      <Column Name="MATHELOAI" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTHELOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TBL_THELOAI_TBL_SACH" Member="TBL_SACHes" ThisKey="MATHELOAI" OtherKey="MATHELOAI" Type="TBL_SACH" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USER" Member="TBL_USERs">
    <Type Name="TBL_USER">
      <Column Name="USERID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PW" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="MAPHANQUYEN" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="TBL_PHANQUYEN_TBL_USER" Member="TBL_PHANQUYEN" ThisKey="MAPHANQUYEN" OtherKey="MAPHANQUYEN" Type="TBL_PHANQUYEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>